/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class proj_net_lbstech_save_as_OpenCV */

#ifndef _Included_proj_net_lbstech_save_as_OpenCV
#define _Included_proj_net_lbstech_save_as_OpenCV
#ifdef __cplusplus
extern "C" {
#endif

    /*
     * Class:     proj_net_lbstech_save_as_OpenCV
     * Method:    getCanny
     * Signature: (Ljava/lang/String;Ljava/lang/String;)V
     */
    JNIEXPORT void JNICALL Java_proj_net_lbstech_save_1as_OpenCVHandler_getCanny
    (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
